# Generated by Django 2.2.5 on 2019-09-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('1', 'STUDENT'), ('2', 'TEACHER')], max_length=20),
        ),
    ]
