# Generated by Django 2.2.5 on 2019-09-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190910_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveIntegerField(choices=[(1, 'STUDENT'), (2, 'TEACHER')]),
        ),
    ]
