# Generated by Django 2.2.5 on 2019-09-11 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190910_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('questions', models.TextField(max_length=1000)),
                ('deadline', models.DateField()),
                ('student', models.ForeignKey(null=True, on_delete=True, related_name='student', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(null=True, on_delete=True, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
