# Generated by Django 2.2.5 on 2019-09-11 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='questions',
        ),
        migrations.AddField(
            model_name='assignment',
            name='document',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
