# Generated by Django 2.2.5 on 2019-09-11 11:30

from django.db import migrations, models
import django.utils.timezone
import myapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190911_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='document',
            field=models.FileField(upload_to='documents/', validators=[myapp.validators.validate_file_extension]),
        ),
    ]
