# Generated by Django 2.2.5 on 2019-09-11 12:08

from django.conf import settings
from django.db import migrations, models
import myapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190911_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_on',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/', validators=[myapp.validators.validate_file_extension])),
                ('title', models.CharField(max_length=50)),
                ('submission_date', models.DateField()),
                ('points', models.FloatField(default=0.0)),
                ('comments', models.CharField(default='', max_length=200)),
                ('assignment', models.ForeignKey(on_delete=True, to='myapp.Assignment')),
                ('from_student', models.ForeignKey(null=True, on_delete=True, related_name='from_student', to=settings.AUTH_USER_MODEL)),
                ('to_teacher', models.ForeignKey(null=True, on_delete=True, related_name='to_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
