# Generated by Django 2.2.5 on 2019-09-11 13:47

from django.db import migrations, models
import myapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190911_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[myapp.validators.validate_file_extension]),
        ),
    ]
