# Generated by Django 2.2.5 on 2019-09-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20190911_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='points',
            field=models.FloatField(default=0.0),
        ),
    ]
