# Generated by Django 2.2.5 on 2019-09-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20190911_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
