# Generated by Django 2.2.5 on 2019-09-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20190912_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
