# Generated by Django 2.2.5 on 2019-09-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20190912_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_date',
            field=models.DateField(blank=True),
        ),
    ]
