# Generated by Django 2.2.5 on 2019-09-12 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20190912_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='points',
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(blank=True, default=0, null=True)),
                ('comments', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('assignment', models.ForeignKey(on_delete=True, to='myapp.Assignment')),
                ('student_from', models.ForeignKey(null=True, on_delete=True, related_name='student_from', to=settings.AUTH_USER_MODEL)),
                ('teacher_to', models.ForeignKey(null=True, on_delete=True, related_name='teacher_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
