# Generated by Django 2.2.5 on 2019-09-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20190912_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, related_name='title', to='myapp.Assignment'),
        ),
    ]
