# Generated by Django 2.2.5 on 2019-09-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20190913_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='assignment',
            new_name='assignment_name',
        ),
    ]
