# Generated by Django 2.2.5 on 2019-09-13 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20190913_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='title',
        ),
    ]
