# Generated by Django 2.2.5 on 2019-09-17 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
