# Generated by Django 2.2.5 on 2019-09-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_message_sent_time'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='message',
            order_with_respect_to='sent_time',
        ),
    ]
