# Generated by Django 2.2.5 on 2019-09-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_auto_20190918_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-sent_time',)},
        ),
    ]
