# Generated by Django 2.2.5 on 2019-09-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_auto_20190918_0927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('sent_time',)},
        ),
    ]
