# Generated by Django 2.2.5 on 2019-09-18 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_auto_20190918_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reciever',
            field=models.ForeignKey(null=True, on_delete=True, related_name='reciever', to=settings.AUTH_USER_MODEL),
        ),
    ]
