# Generated by Django 2.2.5 on 2019-09-18 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_auto_20190918_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=True, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
