# Generated by Django 2.2.5 on 2019-09-18 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_auto_20190918_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
