# Generated by Django 2.2.5 on 2019-09-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_credit_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='user',
        ),
    ]
